cabal-version:       3.6
name:                informath
version:             0.1.0.0
-- synopsis:
-- description:
license:             BSD-3-Clause
author:              Aarne Ranta
maintainer:          aarne.ranta@gmail.com
category:            Development
build-type:          Simple

data-files:
  test/felix-statements.tex

extra-source-files:
  test/felix-cli-test.sh

extra-doc-files:
  doc/felix.md

executable felix2informath
  main-is:             Felix2InformathMain.hs
  other-modules:
    Felix2Informath
    Informath
  hs-source-dirs:      app src
  ghc-options:         -O2
  build-depends:       base >=4.18 && <5,
                       containers,
                       felix,
                       gf >= 3.12,
                       mtl,
                       text
  default-language:    Haskell2010

executable RunInformath
  main-is:             RunInformath.hs
  other-modules:
    DeduktiTheoryAPI
    CommonConcepts
    AnnotateDedukti
    Dedukti2Agda
    Dedukti2Rocq
    Dedukti2Lean
    DeduktiOperations
    Environment
    Informath
    Lexing
    ParseInformath
    Ranking
    Agda.AbsAgda
    Agda.ComposOp
    Agda.PrintAgda
    Rocq.AbsRocq
    Rocq.ComposOp
    Rocq.PrintRocq
    Dedukti.AbsDedukti
    Dedukti.ComposOp
    Dedukti.ErrM
    Dedukti.LexDedukti
    Dedukti.ParDedukti
    Dedukti.PrintDedukti
    Lean.AbsLean
    Lean.ComposOp
    Lean.PrintLean
    BuildConstantTable
    Dedukti2MathCore
    MathCore2Informath
    Informath2MathCore
    MathCore2Dedukti
    InformathAPI
    Utils
    SpecialConstants
    Semantics
    ProofText

  hs-source-dirs:      app src web src/typetheory
  ghc-options:         -O2
  build-depends:       base >=4.18 && <5,
                       containers,
                       mtl,
                       array,
                       json,
                       gf >= 3.12
  default-language:    Haskell2010


test-suite felix-translation
  type:                 exitcode-stdio-1.0
  main-is:              FelixTranslationMain.hs
  hs-source-dirs:       test src
  other-modules:
    Felix2Informath
    Informath
    Paths_informath
  autogen-modules:
    Paths_informath
  build-depends:        base >=4.18 && <5,
                        containers,
                        directory,
                        felix,
                        filepath,
                        gf >= 3.12,
                        mtl,
                        text
  default-language:     Haskell2010
