resolver: lts-22.44
notify-if-nix-on-path: false

packages:
  - .
  - ../felix

extra-deps:
  - effectful-2.6.1.0
  - effectful-core-2.6.1.0
  - gf-3.12
  - strict-mutable-base-1.1.0.0
  - text-builder-1.0.0.4
  - text-builder-core-0.1.1.3
