-- syntactic constructions found in Godement's definitions and theorems
-- that are not (yet) covered by MathCore and MathExtensions
-- the semantics (mapping to MathCore) is in src/GodementSemantics.hs

abstract GodementSyntax = MathExtensions ** {

cat
  DefVerb ;    -- said to be, called, defined to be, by definition
  Condition ;  -- necessary, sufficient, necessary and sufficient
  PropEnum ;   -- a) P ; b) Q ; c) R
  NumDet ;     -- a, no, at least two, exactly n
  Card ;       -- two, n

fun
-- predicates, to be used as relative clauses and in infinitives

  AdjPred : Adj -> Pred ;                   -- is abelian
  Adj2Pred : Adj2 -> Exp -> Pred ;          -- is equal to y
  VerbPred : Verb -> Pred ;                 -- converges
  Verb2Pred : Verb2 -> Exp -> Pred ;        -- contains B
  Noun2Pred : Noun2 -> Exp -> Pred ;        -- is a subgroup of G
  KindPred : Kind -> Pred ;                 -- is a bijective homomorphism
  HavePred : NumDet -> Noun -> Pred ;       -- has at least two subgroups (subgroups of the subject)

-- propositions

  KindProp : Exp -> Kind -> Prop ;          -- f is a bijective homomorphism of G onto H
  NotKindProp : Exp -> Kind -> Prop ;       -- Z is not a field
  HaveProp : Exp -> NumDet -> Noun -> Prop ; -- G has at least two subgroups (of G)

  NecSuffProp : Condition -> Exp -> Pred -> Prop -> Prop ;
      -- for x to be invertible it is necessary and sufficient that P
  necessary_Condition, sufficient_Condition, necsuff_Condition : Condition ;

  EquivalentProp : PropEnum -> Prop ;       -- the following conditions are equivalent: a) P b) Q
  BasePropEnum : Prop -> Prop -> PropEnum ;
  ConsPropEnum : Prop -> PropEnum -> PropEnum ;

  ExistUniqueProp : ArgKind -> Prop -> Prop ;  -- there exists a unique element x of L such that P
  IfSoIsProp : Exp -> Pred -> Exp -> Prop ;    -- if x is reflexible, then so is y
  WheneverProp : Prop -> Prop -> Prop ;        -- P whenever Q
  GivenProp : [ArgKind] -> Prop -> Prop ;      -- given an element x of E, P
  RespProp : Prop -> Prop -> Prop ;            -- P (resp. Q)

-- definitions

  DefAdjJmt : Label -> [Hypo] -> Exp -> DefVerb -> Adj -> Prop -> Jmt ;
      -- a ring K is said to be commutative if P
  DefNounJmt : Label -> [Hypo] -> Exp -> DefVerb -> Kind -> Prop -> Jmt ;
      -- x is said to be a generator of G if P
  DefAdjCJmt : Label -> [Hypo] -> [Exp] -> DefVerb -> AdjC -> Prop -> Jmt ;
      -- G and H are said to be isomorphic if P
  DefAnyKindJmt : Label -> [Hypo] -> Kind -> DefVerb -> Kind -> Jmt ;
      -- a law of composition on X is by definition any mapping of X x X into X
  NamingJmt : Label -> [Hypo] -> Exp -> DefVerb -> Exp -> Jmt ;
      -- p is called the characteristic of K ; the rank of f is defined to be the dimension of Im(f)
  NamingKindJmt : Label -> [Hypo] -> Kind -> DefVerb -> Kind -> Jmt ;
      -- ideals of this type are called principal ideals of K
  WeDefineExpJmt : Label -> [Hypo] -> Exp -> Exp -> Jmt ;
      -- we define the group G^n to be the direct product of G and G^(n-1)
  WeSayJmt : Label -> [Hypo] -> Prop -> Prop -> Jmt ;
      -- we say that G operates on X if P
  DenoteJmt : Label -> [Hypo] -> Exp -> Exp -> Jmt ;
      -- we denote by Hx the set of all elements of G of the form zx
  IsDenotedJmt : Label -> [Hypo] -> Exp -> Exp -> Jmt ;
      -- the set of all left cosets of H is denoted by G/H

  said_DefVerb, called_DefVerb, defined_DefVerb, byDefinition_DefVerb : DefVerb ;

-- naming inside statements

  CalledExp : Exp -> Exp -> Exp ;           -- a subgroup of G, called the kernel of f
  DenotedExp : Exp -> Exp -> Exp ;          -- the kernel of f, denoted by Ker(f)
  SynonymAdj : Adj -> Adj -> Adj ;          -- normal (or invariant)
  SynonymKind : Kind -> Kind -> Kind ;      -- left module over K (or left K-module)
  RespAdj : Adj -> Adj -> Adj ;             -- injective (resp. surjective)

-- kinds

  AdjKind : Adj -> Kind -> Kind ;           -- bijective homomorphism
  PostAdj2Kind : Kind -> Adj2 -> Exp -> Kind ;  -- subgroup of G generated by B
  RelKind : Kind -> Pred -> Kind ;          -- subgroup of G which contains B
  WithPropertyKind : Kind -> Ident -> Prop -> Kind ; -- group G with the property that P
  PropertiesKind : Kind -> PropEnum -> Kind ;
      -- subset of G with the following properties: a) P b) Q ; the variable comes from "let H be"
-- the formulas below are Exp and Prop rather than Term and Declaration,
-- because $...$ parts are indexed before parsing
  OfTheFormKind : Kind -> Exp -> Prop -> Kind ;
      -- element of G of the form $xz$, where $z \in H$
  DeclArgKind : Kind -> Prop -> ArgKind ;          -- element $x \in E$
  DeclSuchThatKind : Kind -> Prop -> Prop -> Kind ; -- element $e \in X$ such that P

-- quantifiers and determiners

  NumDetKindQuant : NumDet -> Kind -> Quant ;  -- at least two subgroups of G
  a_NumDet, no_NumDet : NumDet ;
  AtLeastNumDet, AtMostNumDet, ExactlyNumDet : Card -> NumDet ;
  one_Card, two_Card, three_Card : Card ;
  ExpCard : Exp -> Card ;                      -- n

-- expressions

  TheUniqueExp : ArgKind -> Prop -> Exp ;   -- the unique element x of M such that P
  NumberOfExp : Kind -> Exp ;               -- the number of left cosets of H in G
  SetOfAllExp : Kind -> Exp ;               -- the set of all left cosets of H in G
  NamelyExp : Exp -> Exp -> Exp ;           -- an isomorphism of H onto G, namely f^{-1}
  EndowedExp : Exp -> Exp -> Exp ;          -- the set H, endowed with this law of composition

}
