incomplete concrete GodementExamplesFunctor of GodementExamples =
  Categories
**
open
  Syntax,
  Grammar,
  Utilities,
  Symbolic,
  Prelude
in {

lincat
  Fun3 = {cn : CN ; prep1, prep2, prep3 : Syntax.Prep} ;
  AdjC3 = {ap : AP ; prep : Syntax.Prep} ;
  NegNoun2 = {cn : CN ; prep : Syntax.Prep} ;

oper
  fun3NP : {cn : CN ; prep1, prep2, prep3 : Syntax.Prep} -> NP -> NP -> NP -> NP = \f, x, y, z ->
    mkNP the_Det (mkCN (mkCN (mkCN f.cn (Syntax.mkAdv f.prep1 x)) (Syntax.mkAdv f.prep2 y)) (Syntax.mkAdv f.prep3 z)) ;
  adjC3S : {ap : AP ; prep : Syntax.Prep} -> NP -> NP -> NP -> S = \a, x, y, z ->
    mkS (mkCl (mkNP and_Conj x y) (Grammar.AdvAP a.ap (Syntax.mkAdv a.prep z))) ;
  negNoun2S : {cn : CN ; prep : Syntax.Prep} -> NP -> NP -> S = \n, x, y ->
    mkS negPol (mkCl x (mkCN n.cn (Syntax.mkAdv n.prep y))) ;
  -- as Noun3Prop in Mizar
  noun3S : {cn : CN ; prep1, prep2 : Syntax.Prep} -> NP -> NP -> NP -> S = \n, x, y, z ->
    mkS (mkCl x (mkCN (mkCN n.cn (Syntax.mkAdv n.prep1 y)) (Syntax.mkAdv n.prep2 z))) ;

lin
  Fun3Exp f x y z = fun3NP f x y z ;
  AdjC3Prop a x y z = simpleProp (adjC3S a x y z) ;
  NegNoun2Prop n x y = simpleProp (negNoun2S n x y) ;

  Noun3Example n x y z = mkUtt (noun3S n x y z) ;
  Fun3Example f x y z = mkUtt (fun3NP f x y z) ;
  AdjC3Example a x y z = mkUtt (adjC3S a x y z) ;
  NegNoun2Example n x y = mkUtt (negNoun2S n x y) ;

  NounPrepsFun3 noun p1 p2 p3 = {cn = noun ; prep1 = p1 ; prep2 = p2 ; prep3 = p3} ;
  AdjPrepAdjC3 adj prep = {ap = adj ; prep = prep} ;
  NotNoun2 n = n ;
  NotAdjAdj adj = mkAP (lin AdA {s = "not"}) adj ;

  into_Prep = strPrep "into" ;
  onto_Prep = strPrep "onto" ;
  and_Prep = strPrep "and" ;
  as_Prep = strPrep "as" ;
  among_Prep = strPrep "among" ;
  generated_by_Prep = strPrep "generated by" ;
  spanned_by_Prep = strPrep "spanned by" ;
  defined_by_Prep = strPrep "defined by" ;
  induced_by_Prep = strPrep "induced by" ;
  indexed_by_Prep = strPrep "indexed by" ;
  with_respect_to_Prep = strPrep "with respect to" ;
  relative_to_Prep = strPrep "relative to" ;
  associated_with_Prep = strPrep "associated with" ;
  joining_Prep = strPrep "joining" ;
  with_coefficients_in_Prep = strPrep "with coefficients in" ;
  with_coefficients_Prep = strPrep "with coefficients" ;
  with_exponents_Prep = strPrep "with exponents" ;
  with_masses_Prep = strPrep "with masses" ;
  of_degree_Prep = strPrep "of degree" ;
  of_order_Prep = strPrep "of order" ;

  two_Name = mkName "two" ;
  three_Name = mkName "three" ;

}
