# compare the overlap between two files (e.g. generated by different versions)
# the comparison collects lines that start with an isalpha character

import sys

file1 = sys.argv[1]
file2 = sys.argv[2]

with open(file1) as file:
    lines1 = [line.strip() for line in file if line[:1].isalpha()]
    slines1 = set(lines1)
    
with open(file2) as file:
    lines2 = [line.strip() for line in file if line[:1].isalpha()]
    slines2 = set(lines2)

in1and2 = [line for line in lines1 if line in slines2]

in1not2 = [line for line in lines1 if line not in slines2]

in2not1 = [line for line in lines2 if line not in slines1]

print("# in both", file1, "and", file2)
for line in in1and2:
    print(line)
print()

print("# in", file1, "not in", file2)
for line in in1not2:
    print(line)
print()

print("# in", file2, "not in", file2)
for line in in2not1:
    print(line)
print()    
print("both", len(in1and2), "only", file1, len(in1not2), "only", file2, len(in2not1))

